// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"new-spbatc-drone-platform/internal/database"
	"new-spbatc-drone-platform/internal/routes"
	"new-spbatc-drone-platform/internal/server"
	"new-spbatc-drone-platform/internal/services"
	"new-spbatc-drone-platform/internal/utils"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from injector.go:

func wireRouter(server2 *server.FiberServer, validator *utils.ValidationMiddleware) *routes.Router {
	db := database.NewDB()
	userService := services.NewUserService(db)
	userHandler := &routes.UserHandler{
		Validator:   validator,
		UserService: userService,
	}
	menuService := services.NewMenuService(db)
	menuHandler := &routes.MenuHandler{
		Validator:   validator,
		MenuService: menuService,
	}
	departmentService := services.NewDepartmentService(db)
	departmentHandler := &routes.DepartmentHandler{
		Validator:         validator,
		DepartmentService: departmentService,
	}
	roleService := services.NewRoleService(db)
	roleHandler := &routes.RoleHandler{
		Validator:   validator,
		RoleService: roleService,
	}
	tenantService := services.NewTenantService(db)
	tenantHandler := &routes.TenantHandler{
		Validator:     validator,
		TenantService: tenantService,
	}
	router := routes.NewRouter(server2, userHandler, menuHandler, departmentHandler, roleHandler, tenantHandler)
	return router
}
