// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"gorm.io/gorm"
	"uav_defender/internal/app"
	"uav_defender/internal/app/devices"
	"uav_defender/internal/app/devices/conn"
	"uav_defender/internal/cache"
	"uav_defender/internal/pkg/config"
	"uav_defender/internal/pkg/utils"
	"uav_defender/internal/routes"
	"uav_defender/internal/services"
	"uav_defender/internal/tasks"
)

// Injectors from injector.go:

func wireServer(ctx context.Context, cfg *config.Config, db *gorm.DB, validator *utils.ValidationMiddleware) *app.GinServer {
	commonService := services.NewCommonService(db, validator)
	roleService := services.NewRoleService(db, commonService)
	userService := services.NewUserService(db, commonService, roleService)
	userHandler := &routes.UserHandler{
		CommonService: commonService,
		UserService:   userService,
	}
	menuService := services.NewMenuService(db, commonService)
	menuHandler := &routes.MenuHandler{
		CommonService: commonService,
		MenuService:   menuService,
	}
	roleHandler := &routes.RoleHandler{
		RoleService:   roleService,
		CommonService: commonService,
	}
	deviceService := services.NewDeviceService(db, commonService)
	devicesCache := cache.NewDevicesCache(deviceService)
	deviceHandler := &routes.DeviceHandler{
		Ctx:           ctx,
		DeviceService: deviceService,
		CommonService: commonService,
		DevicesCache:  devicesCache,
	}
	droneTargetService := services.NewDronTargetService(db, commonService)
	droneTargetHandler := &routes.DroneTargetHandler{
		Ctx:                ctx,
		CommonService:      commonService,
		DroneTargetService: droneTargetService,
	}
	fpvWarningDataCache := cache.NewFPVWarningDataCache()
	parseCache := cache.NewParseCache(droneTargetService)
	sseHandler := &routes.SSEHandler{
		Ctx:                 ctx,
		DevicesCache:        devicesCache,
		FPVWarningDataCache: fpvWarningDataCache,
		ParseCache:          parseCache,
	}
	userPublicHandler := &routes.UserPublicHandler{
		CommonService: commonService,
		UserService:   userService,
	}
	router := routes.NewRouter(userHandler, menuHandler, roleHandler, deviceHandler, droneTargetHandler, sseHandler, userPublicHandler)
	decryptTokenCache := cache.NewDecryptTokenCache()
	decryptTokenTask := tasks.NewDecryptTokenTask(ctx, decryptTokenCache)
	devicesTask := tasks.NewDevicesTask(ctx, devicesCache)
	commonCache := cache.NewCommonCache(cfg)
	parseTask := tasks.NewParseTask(ctx, commonCache, parseCache)
	fpvTask := tasks.NewFPVTask(ctx, commonCache, fpvWarningDataCache)
	tasksTasks := tasks.NewTasks(decryptTokenTask, devicesTask, parseTask, fpvTask)
	fpvConnection := conn.NewFPVConnection()
	fpvDevice := devices.NewFPVDevice(ctx, cfg, fpvWarningDataCache, devicesCache, fpvConnection)
	parseConnection := conn.NewParseConnection()
	parseDevice := devices.NewParseDevice(ctx, cfg, decryptTokenCache, parseCache, devicesCache, parseConnection)
	devicesDevices := devices.NewDevices(fpvDevice, parseDevice)
	ginServer := app.NewGinServer(router, tasksTasks, devicesDevices)
	return ginServer
}
